name: Build a package

run-name: Build ${{ inputs.package-id }} with GHC ${{ inputs.ghc-version }}

on:
  workflow_dispatch:
    inputs:
      package-id:
        description: Package to build
        required: true
        type: string
      ghc-version:
        description: GHC version to use
        required: true
        type: choice
        options:
          - 8.10.7
          - 9.0.2
          - 9.2.5
          - 9.4.3
      index-state:
        description: Index state to use
        required: false
        default: HEAD
      documentation:
        description: Enable documentation
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on:
      - ubuntu-22.04

    steps:

      ## sodium
      
      - name: libsodium - cache
        uses: actions/cache@v3
        id: libsodium-cache
        with:
          path: extras/libsodium
          key: libsodium-${{ runner.os }}

      - name: libsodium - checkout
        uses: actions/checkout@v2
        if: steps.libsodium-cache.cache-hit != 'true'
        with:
          repository: input-output-hk/libsodium
          ref: draft-irtf-cfrg-vrf-03
          path: extras/libsodium/src

      - name: libsodium - install
        if: steps.libsodium-cache.cache-hit != 'true'
        working-directory: extras/libsodium/src
        run: |
          ./configure --prefix=${{ github.workspace }}/extras/libsodium
          make
          make install

      - name: libsodium - set PKG_CONFIG_PATH
        run: |
          echo "PKG_CONFIG_PATH=${{ github.workspace }}/extras/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      ## secp256k1
      
      - name: secp256k1 - cache
        uses: actions/cache@v3
        id: secp256k1-cache
        with:
          path: extras/secp256k1
          key: secp256k1-${{ runner.os }}

      - name: secp256k1 - checkout
        uses: actions/checkout@v2
        if: steps.secp256k1-cache.cache-hit != 'true'
        with:
          repository: bitcoin-core/secp256k1
          path: extras/secp256k1/src

      - name: secp256k1 - install
        if: steps.secp256k1-cache.cache-hit != 'true'
        working-directory: extras/secp256k1/src
        run: |
          ./autogen.sh
          ./configure --enable-module-extrakeys --enable-module-schnorrsig --prefix=${{ github.workspace }}/extras/secp256k1
          make
          make install

      - name: secp256k1 - set PKG_CONFIG_PATH
        run: |
          echo "PKG_CONFIG_PATH=${{ github.workspace }}/extras/secp256k1/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      ## GHC toolchain
    
      - name: Set up ghcup cache
        id: ghcup-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.HOME }}/.ghcup
          key: ${{ runner.os }}-${{ inputs.ghc-version }}

      - name: Set up cabal cache
        uses: actions/cache@v3
        with:
          path: ${{ env.HOME }}/.cabal
          key: ${{ runner.os }}-${{ inputs.ghc-version }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ inputs.ghc-version }}

      - name: Install GHC ${{ inputs.ghc-version }}
        id: ghcup-setup
        if: steps.ghcup-cache.cache-hit != 'true'
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ inputs.ghc-version }}
          cabal-version: latest

      - name: Add ghcup bin to path
        if: steps.ghcup-cache.cache-hit == 'true'
        run: echo "$HOME/.ghcup/bin" >> $GITHUB_PATH

      - name: Add cabal bin to path
        run: echo "$HOME/.cabal/bin" >> $GITHUB_PATH

      - name: Build and install cabal-plan
        id: cabal-plan
        run: cabal install cabal-plan --constraint='cabal-plan +exe'
        # A failure here is not essential
        continue-on-error: true

      ## Project

      - name: Checkout project config
        uses: actions/checkout@v2
        with:
          path: project

      - name: Set up project for ${{ inputs.package-id }}
        working-directory: project
        run: |
          # We need at least an empty cabal.project to avoid the implicit one
          touch cabal.project
          # Build cabal.project.local from inputs
          echo 'extra-packages: ${{ inputs.package-id }}' >> cabal.project.local
          echo 'index-state: ${{ inputs.index-state }}' >> cabal.project.local
          if [[ '${{ inputs.documentation }}' == 'true' ]]; then
            echo -e 'package *\n  documentation: True' >> cabal.project.local
          fi
          # Logging
          echo '=================================================='
          echo 'content of cabal.project '
          cat cabal.project
          echo '=================================================='
          echo 'content of cabal.project.local '
          cat cabal.project.local
          echo '=================================================='
          # Parse package-id
          PACKAGE_NAME_REGEX='(.*)(-([0-9]+)(.[0-9]+)*)?$'
          [[ ${{ inputs.package-id }} =~ $PACKAGE_NAME_REGEX ]]
          echo "PACKAGE_NAME=${BASH_REMATCH[1]}" >> $GITHUB_ENV

      - name: Run cabal for project
        working-directory: project
        run: cabal update

      - name: Formulate install plan for ${{ inputs.package-id }}
        working-directory: project
        run: cabal build --dry-run ${{ env.PACKAGE_NAME }}

      - name: Display cabal-plan
        working-directory: project
        # This might not work
        if: ${{ steps.cabal-plan.conclusion == 'success' }}
        run: cabal-plan

      - name: Build ${{ inputs.package-id }} dependencies
        working-directory: project
        run: cabal build ${{ env.PACKAGE_NAME }} --only-dependencies

      - name: Build ${{ inputs.package-id }}
        working-directory: project
        run: cabal build ${{ env.PACKAGE_NAME }}
